### ISSUE TITLE
can you convert it to bottom bar?

### ISSUE THREAD

**Issue by kw2019ltd** [Bernardi23/HeartBeatAppBar#1]
![Screenshot_1554702206](https://user-images.githubusercontent.com/47334522/55701227-136aff80-59db-11e9-8206-c2372fc13a3f.png)

**Comment by Bernardi23** [comment]
You can do it by setting the `HeartBeatAppBar` to the Scaffold's `bottomNavigationBar` property, and also adding the Scaffold's `extendBody` property to `true`. After that, go to HeartBeatAppBar and set its 
``
margin: EdgeInsets.fromLTRB(MediaQuery.of(context).size.width * 0.1, 0, MediaQuery.of(context).size.width * 0.1, 15)
``
Also, the `width` property of the HeartBeatAppBar container can be removed.

Something to note is that the color used to colorize the HeartBeatAppBar is a gradient where one of its colors is not fully opaque. Hence there'll be quite a transparency in the appbar. All of this will be fixed in my next push.

Another thing is that, although you can actually use the buttons of the appbar to push new routes, they'll not be animating. This concept was just for animation purposes, but I'll be trying to add animations to page transitions on my next push aswell.

**Comment by Bernardi23** [comment]
Just pushed the new version. It can now be placed as a child of bottomNavigationBar and hence be used as functional AppBar, has fully opaque colors, and HeartBeatPage has support for routing with animation transitions.

Edit: unfortunately, adding routing affected the performance and there might be some hiccups. I think this could be solved if I used a more efficient state management solution like Bloc.

**Comment by kw2019ltd** [comment]
good tnx, if you can make it as pakcage and it can be customized as botton
app bar when page routing.

**Comment by Bernardi23** [comment]
I don't think I'll be making this a package because it was not the purpose. I made this to practice and show people flutter animations. Also, I wouldn't use this in a real project without asking the permissions to the original designer.

But if you do want to play around with it, or use it in a real project, it's pretty easy to use routing. Just go for one of the appBar icon's `GestureDetector` `onTapUp`method, and pass the function `navigateToScreen` with its parameters (the `context`, the `body` of the next page, the `from` which the animation will start from and the `to` which the animation will end at)
